---
extends:
  - eslint:recommended
  
env:
  browser: false
  commonjs: false
  node: true
  es6: true

parser: babel-eslint

parserOptions:
  sourceType: module
  allowImportExportEverywhere: false
  codeFrame: true

rules:
  no-await-in-loop: error
  no-console: off
  no-else-return: error
  no-empty-function: warn
  no-multi-spaces: error
  curly: warn
  strict: 0
  eqeqeq: error
  no-trailing-spaces: error
  no-duplicate-imports: error
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true

  quotes:
    - error
    - single
    - allowTemplateLiterals: true
      avoidEscape: true

  comma-style:
    - error
    - last

  comma-dangle:
    - error
    - never

  brace-style:
    - error
    - stroustrup
    - allowSingleLine: true